server:
  port: 8082
  servlet:
    context-path: /renren-generator


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/renren_security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#    username: renren
#    password: 123456

    #PostgreSQL配置
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mall_pms
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql、dm】
renren:
  database: postgresql
