spring:
  config:
    import:
      - optional:nacos:application.yml
      - optional:nacos:cos.yml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: thirdparty
        file-extension: yml

